[package]
name = "rust-cards"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.23" }
strum_macros = { version = "0.23" }
rand = "0.8.4"
